FROM openjdk:11 AS builder

RUN apt-get install -y tzdata 
RUN apt-get update -qq && apt-get install -y wget

ENV TZ America/Bogota

VOLUME [ "/home" ]

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=release", "/home/Fineract.war"]




RUN wget -q https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.23/mysql-connector-java-8.0.23.jar